server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  #    routes:
  #      - id: avaliacao_movie-service
  #        uri: lb://movieservice
  #        predicates:
  #          - Path=/movies/**
  #        filters:
  #          - name: CircuitBreaker
  #            args:
  #              name: moviesService
  #              fallbackUri: forward:/fallback/movies
  #      - id: avaliacao_catalog-service
  #        uri: lb://catalogservice
  #        predicates:
  #          - Path=/catalog/**
  #        filters:
  #          - name: CircuitBreaker
  #            args:
  #              name: catalogService
  #              fallbackUri: forward:/fallback/catalog

#queue:
#  movie:
#    name: MovieQueue


