eureka:
  instance:
    hostname: ${INSTANCE:localhost}
  client:
    service-url:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://eurekaserver:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Tulio L. Viglione
  mail: tulio.l.viglione@gmail.com
server:
  port: ${PORT:9999}
message: Generic
